# Generated by Django 5.1.4 on 2025-01-25 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0002_alter_emprestimo_usuario_delete_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='descricao',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='livro',
            name='genero',
            field=models.CharField(default='acao', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='livro',
            name='isbn',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
